export enum Action {
  INDEX = "INDEX",
  NEXT_WORD = "NEXT_WORD",
  NEXT_PAGE = "NEXT_PAGE",
  NEXT_TEN_PAGES = "NEXT_TEN_PAGES",
  TO_END = "TO_END",
  SEARCH = "SEARCH",
  FT_LINK = "FT_LINK",
  PREVIOUS_WORD = "PREVIOUS_WORD",
  PREVIOUS_PAGE = "PREVIOUS_PAGE",
  PREVIOUS_TEN_PAGES = "PREVIOUS_TEN_PAGES",
  TO_START = "TO_START"
}
